AspNetMvcClass/Controllers/DomandeController.cs
using AspNetMvcClass.Models;
using AspNetMvcClass.Models.Data;
using AspNetMvcClass.Models.Domain;
using AspNetMvcClass.Services.DomandeServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspNetMvcClass.Controllers;

[Authorize(Roles = "admin")]
public class DomandeController : Controller
{
    private readonly AuthDbContext dbContext;
    private readonly IDomandeServices services;

    public DomandeController(AuthDbContext dbContext, IDomandeServices domandeServices)
    {
        this.dbContext = dbContext;
        this.services = domandeServices;
    }
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var domande = await services.GetAll();
        return View(domande);
    }
    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(AddDomandaViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            var answerList = new List<string>()
        {
            viewModel.Risposta1,
            viewModel.Risposta2,
            viewModel.Risposta3,
            viewModel.Risposta4
        };
            if (!answerList.Contains(viewModel.RispostaEsatta))
            {
                ModelState.AddModelError("RispostaEsatta", "Deve corrispondere ad almeno una delle altre risposte");
                return View("Add", viewModel);
            }
            await services.Add(viewModel);
            TempData["SuccessMessage"] = "La domanda è stata aggiunta correttamente.";
            return RedirectToAction("Add");
        }
        else
        {
            return View();
        }

    }
    [HttpGet]
    public async Task<IActionResult> View(int id)
    {
       
        var editDomanda = await services.GetById(id);
        if (editDomanda != null)
        {
            var viewModel = new EditDomandaViewModel
            {
                Id = editDomanda.Id,
                Question = editDomanda.Question,
                Risposta1 = editDomanda.Risposta1,
                Risposta2 = editDomanda.Risposta2,
                Risposta3 = editDomanda.Risposta3,
                Risposta4 = editDomanda.Risposta4,
                RispostaEsatta = editDomanda.RispostaEsatta,
                Categoria = editDomanda.Categoria?.ToLower()
            };

            return View("View", viewModel);
        }
        return NotFound();
    }
    [HttpPost]
    public async Task<IActionResult> View(EditDomandaViewModel viewModel)
    {
        if (ModelState.IsValid)
        {
            var answerList = new List<string>()
            {
            viewModel.Risposta1,
            viewModel.Risposta2,
            viewModel.Risposta3,
            viewModel.Risposta4
            };
            if (!answerList.Contains(viewModel.RispostaEsatta))
            {
                ModelState.AddModelError("RispostaEsatta", "Deve corrispondere ad almeno una delle altre risposte");
                return View("View", viewModel);
            }
            await services.Update(viewModel);
            return RedirectToAction("Index");

        }
        else
        {
            return View("View", viewModel);
        }

    }
    [HttpPost]
    public async Task<IActionResult> Delete(EditDomandaViewModel viewModel)
    {
        var domanda = await dbContext.Domande.FindAsync(viewModel.Id);
        if (domanda != null)
        {
            dbContext.Domande.Remove(domanda);
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        return BadRequest("Index");
    }

}

AspNetMvcClass/Controllers/QuizController.cs
using AspNetMvcClass.Models.Data;
using AspNetMvcClass.Models.Domain;
using AspNetMvcClass.Models.ViewModels;
using Azure.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Runtime.CompilerServices;
using System.Security.Claims;
using static System.Net.WebRequestMethods;

namespace AspNetMvcClass.Controllers;

public class QuizController : Controller
{
    private readonly AuthDbContext dbContext;
    
    public QuizController(AuthDbContext dbContext)
    {
        this.dbContext = dbContext;       
    }

    [HttpGet]
    public IActionResult Index()
    {
        HttpContext.Session.Remove("gameSession");
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> InitializeQuizSession(string? category)
    {
        // Check if the game session ID exists in the user's session.
        var gameSessionId = GetGameSessionId();
        // Check if the game session with the specified ID exists in the database.
        var gameSessionExists = await dbContext.GameSessions.AnyAsync(gs => gs.Id == gameSessionId);
        if (gameSessionId.HasValue && gameSessionExists)
        {
            return BadRequest();
        }
        string? userName = null;
        if (User.Identity.IsAuthenticated)
        {           
            userName = User.Identity.Name;
        }
        else
        {            
            userName = "Anonymous";
        }            
        
        var gameSession = new GameSession()
        {
            CurrentQuestionIndex = 0,
            Score = 0,
            UserId = userName,
            CreatedAt = DateTime.Now,
            Questions = await dbContext.Domande
            .Where(d => d.Categoria == category)
            .OrderBy(y => Guid.NewGuid())
            .Take(8)
            .ToListAsync()
        };
       
        await dbContext.GameSessions.AddAsync(gameSession);
        await dbContext.SaveChangesAsync();

        // Store the game session ID in the user's session.
        HttpContext.Session.SetInt32("gameSession", gameSession.Id);

        return RedirectToAction("QuizViews");
    }

    [HttpGet]
    public async Task<IActionResult> QuizViews()
    {
        var gameSessionId = GetGameSessionId();
        if (gameSessionId.HasValue)
        {
            // Retrieve the game session from the database.
            var gameSession = await dbContext.GameSessions
                .Include(gs => gs.Questions)
                .SingleOrDefaultAsync(gs => gs.Id == gameSessionId);

            if (gameSession != null && gameSession.CurrentQuestionIndex < gameSession.Questions.Count)
            {               
                var currentQuestion = gameSession.Questions[gameSession.CurrentQuestionIndex];
                return View(currentQuestion);
            }
            else
            {                
                if (gameSession.CurrentQuestionIndex == gameSession.Questions.Count)
                {                    
                    return RedirectToAction("Score");
                }
            }
        }

        return BadRequest();
    }

    [HttpPost]
    public async Task<IActionResult> QuizViews(string answer)
    {
       
        var gameSessionId = GetGameSessionId();
        
        if (gameSessionId.HasValue)
        {
            
            var gameSession = await dbContext.GameSessions
                .Include(gs => gs.Questions)
                .SingleOrDefaultAsync(gs => gs.Id == gameSessionId);
            
            if (gameSession != null && gameSession.CurrentQuestionIndex < gameSession.Questions.Count)
            {                
                var currentQuestion = gameSession.Questions[gameSession.CurrentQuestionIndex];
                var userAnswer = answer;
                
                if (userAnswer == currentQuestion.RispostaEsatta)
                {                    
                    gameSession.Score++;
                }
                
                gameSession.CurrentQuestionIndex++;
               
                dbContext.GameSessions.Update(gameSession);
                await dbContext.SaveChangesAsync();
                
                return RedirectToAction("QuizViews");
            }
        }

        return BadRequest();
    }





    [HttpGet]
    public async Task<IActionResult> Score()
    {
       
        var gameSessionId = GetGameSessionId();
        //Rest user session
        HttpContext.Session.Remove("gameSession");
        
        if (gameSessionId.HasValue)
        {            
            var gameSession = await dbContext.GameSessions
                .SingleOrDefaultAsync(gs => gs.Id == gameSessionId);

            
            if (gameSession != null)
            {
                ScoreViewModel scoreModel = new ScoreViewModel
                {
                    Score = gameSession.Score,
                    TotalQuestions = gameSession.CurrentQuestionIndex
                };
                int winPointsNeeded = (int)(gameSession.CurrentQuestionIndex * 0.75);
                if (winPointsNeeded <= gameSession.Score)
                {
                    return View("Win", scoreModel);
                }
                else
                {
                    return View("Lose", scoreModel);
                }
                
            }
        }

        return BadRequest();
    }



    //private async Task<GameSession> GetGameSessionForUserAsync()
    //{
    //    int? gameSessionId = GetGameSessionId();
    //    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

    //    return await dbContext.GameSessions
    //        .Include(x => x.Questions)
    //        .FirstOrDefaultAsync(x => x.Id == gameSessionId.Value && x.UserId == userId);
    //}

    private int? GetGameSessionId()
    {
       return HttpContext.Session.GetInt32("gameSession");
       
    }
}

AspNetMvcClass/Controllers/UserController.cs
using AspNetMvcClass.Models.Data;
using AspNetMvcClass.Models.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AspNetMvcClass.Controllers;

public class UserController : Controller
{

    private readonly UserManager<IdentityUser> userManager;
    private readonly SignInManager<IdentityUser> signInManager;
    private readonly RoleManager<IdentityRole> roleManager;

    public UserController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RoleManager<IdentityRole> roleManager)
    {
        this.userManager = userManager;
        this.signInManager = signInManager;
        this.roleManager = roleManager;       
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegisterUserViewModel model)
    {
        if (ModelState.IsValid)
        {
            var user = new IdentityUser
            {
                UserName = model.Email,
                Email = model.Email
            };
            var result = await userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                await signInManager.SignInAsync(user, isPersistent: false);
                return RedirectToAction("Index", "Home");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

        }
        return await Task.Run(() => View("Register", model));
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginViewModel model)
    {
        if (ModelState.IsValid)
        {           
            var identityResult = await signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
            if (identityResult.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Email o Password incorretta");
        }
        return await Task.Run(() => View("Login", model));
    }

    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        await signInManager.SignOutAsync();
        return RedirectToAction("Login");
    }
    [HttpGet]
    public IActionResult AssignRole()
    {
        return View();
    }
    //[HttpPost]
    //public async Task<IActionResult> AssignRole(string userEmail, string roleName)
    //{
    //    // Get the user and the role using the email address and role name
    //    var user = await userManager.FindByEmailAsync(userEmail);
    //    var role = await roleManager.FindByNameAsync(roleName);
    //    if (role == null)
    //    {
    //        await roleManager.CreateAsync(new IdentityRole { Name = $"{roleName}" });
    //    }

    //    // Add the user to the role
    //    var result = await userManager.AddToRoleAsync(user, roleName);

    //    // Check if the operation was successful
    //    if (result.Succeeded)
    //    {
    //        // The user was added to the role
    //    }
    //    else
    //    {
    //        // There was an error adding the user to the role
    //    }
    //    return RedirectToAction("Login");
    //    //Task.Run(async () =>
    //    //{
    //    //    await roleManager.CreateAsync(new IdentityRole { Name = "admin" });
    //    //    await AssignRole("ex@gmail.com", "admin");
    //    //});
    //}

    //private async Task MasterLogin(LoginViewModel model)
    //{
    //    if (model.Email == "****" && model.Password == "*****")
    //    {
    //        var claims = new List<Claim>()
    //        {
    //            new Claim(ClaimTypes.Email, "Admin@Libero.it"),
    //            new Claim("Master", "MasterAccount")
    //        };
    //        var identity = new ClaimsIdentity(claims, "MyCookieAuth");
    //        ClaimsPrincipal principal = new(identity);
    //        await HttpContext.SignInAsync("MyCookieAuth", principal);
    //    }
    //}
}

AspNetMvcClass/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - QuizzGame</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/AspNetMvcClass.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/MyBackGrounds.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">


</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-img-ambiente border-bottom border-dark box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>QuizzGame</strong></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					@if (!SignInManager.IsSignedIn(User))
					{
						<ul class="navbar-nav flex-grow-1">
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="Index"><strong>Menu</strong></a>
							</li>
						</ul>
						<ul class="navbar-nav d-flex justify-content-end">
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register"><strong>Registrati</strong></a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login"><strong>Login</strong></a>
							</li>
						</ul>
					}
					else
					{
						@if (User.IsInRole("admin"))
						{
							<ul class="navbar-nav flex-grow-1">
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="Index"><strong>Menu</strong></a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Domande" asp-action="Index"><strong>Domande</strong></a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Domande" asp-action="Add"><strong>Aggiungi Domanda</strong></a>
								</li>								
							</ul>
							<ul class="navbar-nav d-flex justify-content-end">
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout"><strong>Logout</strong></a>
								</li>
							</ul>
						}
						else
						{
							<ul class="navbar-nav flex-grow-1">
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="Quiz" asp-action="Index"><strong>Menu</strong></a>
								</li>
							</ul>
							<ul class="navbar-nav d-flex justify-content-end">
								<li class="nav-item">
									<a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout"><strong>Logout</strong></a>
								</li>
							</ul>
						}

						
					}
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	<div id="countdown"></div>


	<footer class="border-top border-dark footer bg-img-ambiente container-fluid">
		&copy; 2022 - Neo.Fi.Lia
		<a href="https://www.instagram.com/neo.fi.lia/?hl=it">
			<i class="bi bi-instagram"></i>
		</a>
	</footer>
	@*<script>
		// Set the countdown duration in seconds
var countdownDuration = 900; // 15 minutes

// Update the countdown every 1 second
var countdownInterval = setInterval(function () {
  // Make an AJAX request to get the current countdown time from the server
  $.get("/cdtimer", function (data) {
    // Update the countdown element with the time remaining
    document.getElementById("countdown").innerHTML = data.remainingDuration;

    // If the countdown is complete, clear the interval and display a message
    if (data.remainingDuration == 0) {
      clearInterval(countdownInterval);
      document.getElementById("countdown").innerHTML = "Event!";
    }
  });
}, 1000);

	</script>*@

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>